"""Linux platform setup — udev, SELinux, polkit, desktop entry.

Owns all Linux system configuration logic. CLI is a thin wrapper
that calls these functions — never the other way around.
"""
from __future__ import annotations

import logging
import os
import shutil
import site
import subprocess
import sys
from pathlib import Path
from typing import Any

from trcc.core.platform import is_root
from trcc.core.ports import PlatformSetup

log = logging.getLogger(__name__)


# =========================================================================
# Privilege escalation helpers
# =========================================================================

def _real_user_home() -> Path:
    """Return the real (non-root) user's home directory.

    Under sudo, ``Path.home()`` returns ``/root/``.  Check ``SUDO_USER``
    first so that desktop entries and icons land in the actual user's
    ``~/.local/`` instead of root's.
    """
    sudo_user = os.environ.get("SUDO_USER")
    if sudo_user and sudo_user != "root":
        import pwd
        return Path(pwd.getpwnam(sudo_user).pw_dir)
    return Path.home()


def sudo_reexec(subcommand: str) -> int:
    """Re-exec `trcc <subcommand>` as root via sudo with correct PYTHONPATH.

    sudo strips user site-packages (~/.local/lib), so we include both
    the trcc package root and all site-packages where dependencies live.
    """
    paths: list[str] = []
    paths.extend(site.getsitepackages())
    paths.append(site.getusersitepackages())
    trcc_pkg = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    paths.append(trcc_pkg)
    pythonpath = os.pathsep.join(paths)
    cmd = [
        "sudo", "env", f"PYTHONPATH={pythonpath}",
        sys.executable, "-m", "trcc.cli", subcommand,
    ]
    print("Root required — requesting sudo...")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"\n  sudo re-exec failed (exit {result.returncode}).")
        print(f"  Try running directly:  sudo trcc {subcommand}")
        print(f"  Or with full path:     sudo {sys.executable} -m trcc.cli {subcommand}")
    return result.returncode


# =========================================================================
# System configuration functions
# =========================================================================

def setup_rapl_permissions() -> None:
    """Make Intel/AMD RAPL energy counters readable by non-root users."""
    rapl_base = Path("/sys/class/powercap")
    if not rapl_base.exists():
        return

    energy_files = sorted(rapl_base.glob("intel-rapl:*/energy_uj"))
    if not energy_files:
        return

    tmpfiles_path = "/etc/tmpfiles.d/trcc-rapl.conf"
    lines = [
        "# Thermalright TRCC — allow non-root CPU power reading (RAPL)",
        "# Auto-generated by trcc setup-udev",
    ]
    for energy_file in energy_files:
        lines.append(f"z {energy_file} 0444 root root -")
    tmpfiles_content = "\n".join(lines) + "\n"

    with open(tmpfiles_path, "w") as f:
        f.write(tmpfiles_content)
    print(f"Wrote {tmpfiles_path}")

    for energy_file in energy_files:
        try:
            energy_file.chmod(0o444)
        except OSError:
            pass
    print(f"RAPL power sensors: {len(energy_files)} domain(s) made readable")

    restorecon = subprocess.run(
        ["which", "restorecon"], capture_output=True, text=True,
    )
    if restorecon.returncode == 0:
        subprocess.run(
            ["restorecon", tmpfiles_path], capture_output=True, check=False,
        )


def setup_udev(dry_run: bool = False) -> int:
    """Generate and install udev rules + USB storage quirks from KNOWN_DEVICES."""
    from trcc.adapters.device.detector import (
        _BULK_DEVICES,
        _HID_LCD_DEVICES,
        _LED_DEVICES,
        _LY_DEVICES,
        KNOWN_DEVICES,
    )

    all_devices = {**KNOWN_DEVICES, **_HID_LCD_DEVICES, **_LED_DEVICES, **_BULK_DEVICES, **_LY_DEVICES}

    rules_path = "/etc/udev/rules.d/99-trcc-lcd.rules"
    rules_lines = ["# Thermalright LCD/LED cooler devices — auto-generated by trcc setup-udev"]

    from trcc.core.models import PROTOCOL_TRAITS

    for (vid, pid), info in sorted(all_devices.items()):
        vendor = info.vendor
        product = info.product
        traits = PROTOCOL_TRAITS.get(info.protocol, PROTOCOL_TRAITS['scsi'])
        rule_parts = [f'# {vendor} {product}']
        for subsystem in traits.udev_subsystems:
            attr = 'ATTRS' if subsystem in ('hidraw', 'scsi_generic') else 'ATTR'
            rule_parts.append(
                f'SUBSYSTEM=="{subsystem}", '
                f'{attr}{{idVendor}}=="{vid:04x}", '
                f'{attr}{{idProduct}}=="{pid:04x}", '
                f'MODE="0666"'
            )
        rules_lines.append('\n'.join(rule_parts))

    rules_content = "\n\n".join(rules_lines) + "\n"

    quirk_entries = [f"{vid:04x}:{pid:04x}:u" for vid, pid in sorted(KNOWN_DEVICES)]
    quirks_param = ",".join(quirk_entries)

    modprobe_path = "/etc/modprobe.d/trcc-lcd.conf"
    modprobe_content = (
        "# Thermalright LCD — force usb-storage bulk-only (bypass UAS)\n"
        "# Without this, devices are ignored and /dev/sgX is never created\n"
        "# Auto-generated by trcc setup-udev\n"
        f"options usb-storage quirks={quirks_param}\n"
    )

    if dry_run:
        print("=== udev rules ===")
        print(rules_content)
        print(f"# Would write to {rules_path}\n")
        print("=== usb-storage quirks ===")
        print(modprobe_content)
        print(f"# Would write to {modprobe_path}\n")
        print("=== sg module autoload ===")
        print("sg")
        print("# Would write to /etc/modules-load.d/trcc-sg.conf")
        return 0

    if not is_root():
        return sudo_reexec("setup-udev")

    with open(rules_path, "w") as f:
        f.write(rules_content)
    print(f"Wrote {rules_path}")

    with open(modprobe_path, "w") as f:
        f.write(modprobe_content)
    print(f"Wrote {modprobe_path}")

    quirks_sysfs = "/sys/module/usb_storage/parameters/quirks"
    if os.path.exists(quirks_sysfs):
        with open(quirks_sysfs, "w") as f:
            f.write(quirks_param)
        print(f"Applied quirks: {quirks_param}")

    modules_load_path = "/etc/modules-load.d/trcc-sg.conf"
    modules_load_content = (
        "# Thermalright LCD — ensure SCSI generic (/dev/sgX) is available\n"
        "# Without this, some distros only create /dev/sdX for USB mass storage\n"
        "# Auto-generated by trcc setup-udev\n"
        "sg\n"
    )
    with open(modules_load_path, "w") as f:
        f.write(modules_load_content)
    print(f"Wrote {modules_load_path}")

    subprocess.run(["modprobe", "sg"], check=False, capture_output=True)

    setup_rapl_permissions()

    subprocess.run(["udevadm", "control", "--reload-rules"], check=False)
    subprocess.run(["udevadm", "trigger"], check=False)
    print("\nDone. Unplug and replug the USB cable (or reboot if it's not easily accessible).")
    return 0


def setup_selinux() -> int:
    """Install SELinux policy module allowing USB device access."""
    import tempfile

    if not is_root():
        return sudo_reexec("setup-selinux")

    try:
        r = subprocess.run(
            ["getenforce"], capture_output=True, text=True, timeout=5,
        )
        status = r.stdout.strip().lower()
    except FileNotFoundError:
        print("SELinux not installed — nothing to do.")
        return 0

    if status != 'enforcing':
        print(f"SELinux is {status} — no policy needed.")
        return 0

    try:
        r = subprocess.run(
            ["semodule", "-l"], capture_output=True, text=True, timeout=10,
        )
        if 'trcc_usb' in r.stdout:
            print("SELinux module trcc_usb already loaded.")
            return 0
    except FileNotFoundError:
        print("semodule not found — cannot manage SELinux policies.")
        return 1

    from trcc.adapters.infra.doctor import _detect_pkg_manager, _install_hint
    pm = _detect_pkg_manager()

    missing: list[str] = []
    for tool in ('checkmodule', 'semodule_package'):
        if not shutil.which(tool):
            missing.append(tool)
    if missing:
        for tool in missing:
            print(f"  {tool} not found — {_install_hint(tool, pm)}")
        return 1

    trcc_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    te_src = os.path.join(trcc_root, 'data', 'trcc_usb.te')
    if not os.path.isfile(te_src):
        print(f"SELinux policy source not found: {te_src}")
        return 1

    try:
        with tempfile.TemporaryDirectory() as tmp:
            te_path = os.path.join(tmp, 'trcc_usb.te')
            mod_path = os.path.join(tmp, 'trcc_usb.mod')
            pp_path = os.path.join(tmp, 'trcc_usb.pp')

            shutil.copy2(te_src, te_path)

            r = subprocess.run(
                ['checkmodule', '-M', '-m', '-o', mod_path, te_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                print(f"checkmodule failed: {r.stderr.strip()}")
                return 1

            r = subprocess.run(
                ['semodule_package', '-o', pp_path, '-m', mod_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                print(f"semodule_package failed: {r.stderr.strip()}")
                return 1

            r = subprocess.run(
                ['semodule', '-i', pp_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                print(f"semodule install failed: {r.stderr.strip()}")
                return 1

        print("Installed SELinux module trcc_usb (USB device access for TRCC).")
        return 0

    except Exception as e:
        print(f"Error installing SELinux policy: {e}")
        return 1


def install_desktop() -> int:
    """Install .desktop menu entry and icon for app launchers."""
    home = _real_user_home()
    app_dir = home / ".local" / "share" / "applications"

    pkg_root = Path(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    icon_pkg_dir = pkg_root / "assets" / "icons"
    desktop_src = pkg_root / "assets" / "trcc-linux.desktop"

    app_dir.mkdir(parents=True, exist_ok=True)
    desktop_dst = app_dir / "trcc-linux.desktop"
    if desktop_src.exists():
        shutil.copy2(desktop_src, desktop_dst)
    else:
        desktop_dst.write_text(
            "[Desktop Entry]\nName=TRCC Linux\n"
            "Comment=Thermalright LCD Control Center\nExec=trcc gui\n"
            "Icon=trcc\nTerminal=false\nType=Application\n"
            "Categories=Utility;System;\n"
            "Keywords=thermalright;lcd;cooler;aio;cpu;\n"
            "StartupWMClass=trcc-linux\n"
        )
    print(f"Installed {desktop_dst}")

    installed_icon = False
    for size in [256, 128, 64, 48, 32, 24, 16]:
        icon_src = icon_pkg_dir / f"trcc_{size}x{size}.png"
        if icon_src.exists():
            icon_dir = home / ".local" / "share" / "icons" / "hicolor" / f"{size}x{size}" / "apps"
            icon_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(icon_src, icon_dir / "trcc.png")
            installed_icon = True

    if installed_icon:
        subprocess.run(
            ["gtk-update-icon-cache", str(home / ".local" / "share" / "icons" / "hicolor")],
            check=False, capture_output=True
        )
    else:
        print("Warning: icons not found, menu entry will use a generic icon")

    print("\nTRCC should now appear in your application menu.")
    print("If it doesn't show up immediately, log out and back in.")
    return 0


def setup_polkit() -> int:
    """Install polkit policy for passwordless dmidecode/smartctl access."""
    if not is_root():
        return sudo_reexec("setup-polkit")

    pkg_root = Path(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    policy_src = pkg_root / "assets" / "com.github.lexonight1.trcc.policy"

    if not policy_src.exists():
        print(f"Policy file not found: {policy_src}")
        return 1

    policy_text = policy_src.read_text()
    for binary in ('dmidecode', 'smartctl'):
        found = shutil.which(binary)
        if found:
            real_path = os.path.realpath(found)
            policy_text = policy_text.replace(f'/usr/bin/{binary}', real_path)

    policy_dst = Path("/usr/share/polkit-1/actions/com.github.lexonight1.trcc.policy")
    policy_dst.parent.mkdir(parents=True, exist_ok=True)
    policy_dst.write_text(policy_text)

    invoking_user = os.environ.get('SUDO_USER', '')
    if invoking_user:
        rules_dst = Path("/etc/polkit-1/rules.d/50-trcc.rules")
        rules_dst.parent.mkdir(parents=True, exist_ok=True)
        rules_dst.write_text(
            '// TRCC Linux — passwordless dmidecode/smartctl for installing user\n'
            'polkit.addRule(function(action, subject) {\n'
            '    if ((action.id == "com.github.lexonight1.trcc.dmidecode" ||\n'
            '         action.id == "com.github.lexonight1.trcc.smartctl") &&\n'
            f'        subject.user == "{invoking_user}") {{\n'
            '        return polkit.Result.YES;\n'
            '    }\n'
            '});\n'
        )
        print(f"Installed {rules_dst} (user: {invoking_user})")

    restore_paths = [str(policy_dst)]
    if invoking_user:
        restore_paths.append(str(rules_dst))
    if shutil.which('restorecon'):
        subprocess.run(['restorecon'] + restore_paths, check=False)
    print(f"Installed {policy_dst}")
    print(f"User '{invoking_user}' can now run dmidecode/smartctl without a password.")
    return 0


class LinuxSetup(PlatformSetup):
    """Linux setup wizard — system deps, GPU, udev, SELinux, polkit, desktop."""

    def get_distro_name(self) -> str:
        from trcc.adapters.infra.doctor import _read_os_release
        return _read_os_release().get('PRETTY_NAME', 'Unknown Linux')

    def get_pkg_manager(self) -> str | None:
        from trcc.adapters.infra.doctor import _detect_pkg_manager
        return _detect_pkg_manager()

    def check_deps(self) -> list[Any]:
        from trcc.adapters.infra.doctor import check_system_deps
        return check_system_deps(self.get_pkg_manager())

    def config_dir(self) -> str:
        from trcc.core.paths import USER_CONFIG_DIR
        return USER_CONFIG_DIR

    def data_dir(self) -> str:
        from trcc.core.paths import USER_DATA_DIR
        return USER_DATA_DIR

    def user_content_dir(self) -> str:
        from trcc.core.paths import USER_CONTENT_DIR
        return USER_CONTENT_DIR

    def theme_dir(self, width: int, height: int) -> str:
        from trcc.core.paths import DATA_DIR
        return os.path.join(DATA_DIR, f'theme{width}{height}')

    def web_dir(self, width: int, height: int) -> str:
        from trcc.core.paths import get_web_dir
        return get_web_dir(width, height)

    def web_masks_dir(self, width: int, height: int) -> str:
        from trcc.core.paths import get_web_masks_dir
        return get_web_masks_dir(width, height)

    def user_masks_dir(self, width: int, height: int) -> str:
        from trcc.core.paths import get_user_masks_dir
        return get_user_masks_dir(width, height)

    def ffmpeg_install_help(self) -> str:
        from trcc.adapters.infra.doctor import _detect_pkg_manager, _install_hint
        pm = _detect_pkg_manager()
        hint = _install_hint('ffmpeg', pm)
        return f"ffmpeg not found. Install:\n  {hint}" if hint else "ffmpeg not found"

    def resolve_assets_dir(self, pkg_assets_dir: Path) -> Path:
        """Linux: use package dir directly — no sandboxing issues."""
        return pkg_assets_dir

    def archive_tool_install_help(self) -> str:
        from trcc.adapters.infra.doctor import _install_hint
        pm = self.get_pkg_manager()
        hint = _install_hint('7z', pm)
        if hint:
            return f"7z not found. Install:\n  {hint}"
        return (
            "7z not found. Install p7zip for your distro:\n"
            "  Fedora/RHEL:    sudo dnf install p7zip p7zip-plugins\n"
            "  Ubuntu/Debian:  sudo apt install p7zip-full\n"
            "  Arch:           sudo pacman -S p7zip"
        )

    def run(self, auto_yes: bool = False) -> int:
        from trcc.adapters.infra.doctor import (
            check_desktop_entry,
            check_gpu,
            check_polkit,
            check_rapl,
            check_selinux,
            check_system_deps,
            check_udev,
        )

        pm = self.get_pkg_manager()
        print(f"\n  TRCC Setup — {self.get_distro_name()}\n")
        actions: list[str] = []

        # Step 1/6: System dependencies
        print("  Step 1/6: System dependencies")
        deps = check_system_deps(pm)
        missing_required: list[str] = []
        missing_optional: list[str] = []
        for dep in deps:
            if dep.ok:
                ver = f" {dep.version}" if dep.version else ""
                print(f"    [OK]  {dep.name}{ver}")
            elif dep.required:
                note = f" ({dep.note})" if dep.note else ""
                print(f"    [!!]  {dep.name} — MISSING{note}")
                missing_required.append(dep.install_cmd)
            else:
                note = f" ({dep.note})" if dep.note else ""
                print(f"    [--]  {dep.name} — not installed{note}")
                missing_optional.append(dep.install_cmd)

        for cmd in missing_required:
            if _confirm(f"Install? -> {cmd}", auto_yes):
                print(f"    -> {cmd}")
                import shlex
                result = subprocess.run(shlex.split(cmd))
                if result.returncode == 0:
                    actions.append(f"Installed: {cmd}")
                else:
                    print(f"    [!!] Command failed (exit {result.returncode})")
        for cmd in missing_optional:
            if _confirm(f"Install? -> {cmd}", auto_yes):
                print(f"    -> {cmd}")
                import shlex
                result = subprocess.run(shlex.split(cmd))
                if result.returncode == 0:
                    actions.append(f"Installed: {cmd}")
        print()

        # Step 2/6: GPU detection
        print("  Step 2/6: GPU detection")
        gpus = check_gpu()
        if not gpus:
            print("    [--]  No discrete GPU detected")
        for gpu in gpus:
            if gpu.package_installed:
                print(f"    [OK]  {gpu.label}")
            else:
                print(f"    [--]  {gpu.label} — {gpu.install_cmd}")
                if _confirm(f"Install? -> {gpu.install_cmd}", auto_yes):
                    print(f"    -> {gpu.install_cmd}")
                    result = subprocess.run(
                        [sys.executable, "-m", "pip", "install"]
                        + gpu.install_cmd.split()[-1:],
                    )
                    if result.returncode == 0:
                        actions.append(f"Installed: {gpu.install_cmd}")
                    else:
                        print(f"    [!!] pip failed (exit {result.returncode})")
        print()

        # Step 3/6: USB device permissions (udev + RAPL)
        print("  Step 3/6: USB device permissions")
        udev = check_udev()
        if udev.ok:
            print(f"    [OK]  {udev.message}")
        else:
            print(f"    [!!]  {udev.message}")
            if _confirm("Install udev rules? (requires sudo)", auto_yes):
                rc = setup_udev()
                if rc == 0:
                    actions.append("Installed udev rules")
                else:
                    print("    [!!] udev setup failed")

        rapl = check_rapl()
        if rapl.applicable:
            if rapl.ok:
                print(f"    [OK]  {rapl.message}")
            else:
                print(f"    [--]  {rapl.message}")
                if _confirm("Fix RAPL permissions? (requires sudo)", auto_yes):
                    if not is_root():
                        rc = sudo_reexec("setup-udev")
                    else:
                        setup_rapl_permissions()
                        rc = 0
                    if rc == 0:
                        actions.append("Fixed RAPL power sensor permissions")
        print()

        # Step 4/6: SELinux policy
        se = check_selinux()
        if se.enforcing:
            print("  Step 4/6: SELinux policy")
            if se.ok:
                print(f"    [OK]  {se.message}")
            else:
                print(f"    [!!]  {se.message}")
                if _confirm("Install SELinux USB policy? (requires sudo)", auto_yes):
                    rc = setup_selinux()
                    if rc == 0:
                        actions.append("Installed SELinux policy")
                    else:
                        print("    [!!] SELinux setup failed")
            print()

        # Step 5/6: Polkit policy
        print("  Step 5/6: Hardware info access")
        pk = check_polkit()
        if pk.ok:
            print(f"    [OK]  {pk.message}")
        else:
            print(f"    [--]  {pk.message}")
            if _confirm("Install polkit policy for hardware info? (requires sudo)", auto_yes):
                rc = setup_polkit()
                if rc == 0:
                    actions.append("Installed polkit policy")
                else:
                    print("    [!!] polkit setup failed")
        print()

        # Step 6/6: Desktop integration
        print("  Step 6/6: Desktop integration")
        if check_desktop_entry():
            print("    [OK]  Application menu entry installed")
        else:
            print("    [--]  No application menu entry")
            if _confirm("Install application menu entry?", auto_yes):
                rc = install_desktop()
                if rc == 0:
                    actions.append("Installed desktop entry")
        print()

        _print_summary(actions)
        return 0


def _confirm(prompt: str, auto_yes: bool) -> bool:
    if auto_yes:
        print(f"  {prompt} [Y/n]: y (auto)")
        return True
    try:
        answer = input(f"  {prompt} [Y/n]: ").strip().lower()
        return answer in ('', 'y', 'yes')
    except (EOFError, KeyboardInterrupt):
        print()
        return False


def _print_summary(actions: list[str]) -> None:
    print("  Summary")
    if actions:
        for a in actions:
            print(f"    + {a}")
    else:
        print("    Nothing to do — system is ready.")
    print("\n  Run 'trcc gui' to launch, or find TRCC in your app menu.\n")
