"""SMC electrical sensor metadata from iSMC smc/sensors.go (GPL-3.0).

Auto-generated — Key → (human name, category, unit).
"""
from __future__ import annotations

ISMCSMC_POWER: dict[str, tuple[str, str, str]] = {
    "PC%C": ("CPU Core %", "power", "W"),
    "PCAM": ("CPU Core (IMON)", "power", "W"),
    "PCPC": ("CPU Package", "power", "W"),
    "PCTR": ("CPU Total", "power", "W"),
    "PCPT": ("CPU Package Total", "power", "W"),
    "PCPR": ("CPU Package Total (SMC)", "power", "W"),
    "PC%R": ("CPU Computing High Side %", "power", "W"),
    "PC%G": ("CPU GFX %", "power", "W"),
    "PCEC": ("CPU VccEDRAM", "power", "W"),
    "PCPG": ("GPU Intel Graphics", "power", "W"),
    "PG%R": ("GPU %", "power", "W"),
    "PCGC": ("Intel GPU", "power", "W"),
    "PCGM": ("Intel GPU (IMON)", "power", "W"),
    "PC3C": ("RAM", "power", "W"),
    "PPBR": ("Battery", "power", "W"),
    "PDTR": ("DC In", "power", "W"),
    "PSTR": ("System Total", "power", "W"),
    "PCPD": ("CPU DRAM", "power", "W"),
    "PCPL": ("CPU Total", "power", "W"),
    "PM0R": ("Memory Rail", "power", "W"),
    "PN0C": ("MCH", "power", "W"),
    "PN1R": ("PCH Rail", "power", "W"),
    "PD0R": ("Mainboard S0 Rail", "power", "W"),
    "PD5R": ("Mainboard S5 Rail", "power", "W"),
    "PH02": ("Main 3.3V Rail", "power", "W"),
    "PH05": ("Main 5V Rail", "power", "W"),
    "Pp0R": ("12V Rail", "power", "W"),
    "PD2R": ("Main 12V Rail", "power", "W"),
    "PO0R": ("Misc. Rail", "power", "W"),
    "PBLC": ("Battery Rail", "power", "W"),
    "PB0R": ("Battery Rail", "power", "W"),
    "P50R": ("5V Low-Side", "power", "W"),
    "PAPC": ("Airport", "power", "W"),
    "PB1R": ("Discrete BMON On Battery", "power", "W"),
    "PC0I": ("CPU I/O High Side", "power", "W"),
    "PC0M": ("CPU Mem Load-Side", "power", "W"),
    "PC0S": ("CPU SA High Side", "power", "W"),
    "PCLT": ("CPU Package Total", "power", "W"),
    "PCS0": ("Chipset Low-Side", "power", "W"),
    "PCS1": ("Chipset IMon", "power", "W"),
    "PD0D": ("Power Supply Trend", "power", "W"),
    "PD0E": ("Power Supply Filtered", "power", "W"),
    "PD0F": ("Power Supply Filtered Adjusted", "power", "W"),
    "PD0J": ("Power Supply Max Error Filtered Output", "power", "W"),
    "PD1R": ("Average CPU 1V5", "power", "W"),
    "PG0A": ("GPU Aux Load-Side", "power", "W"),
    "PG0C": ("GPU", "power", "W"),
    "PG0F": ("GPU Frame Buf Input-Side", "power", "W"),
    "PG0I": ("GPU VDDCI Load-Side", "power", "W"),
    "PG0M": ("GPU Mem Ctl Load-Side", "power", "W"),
    "PG0S": ("GPU A VDDCI Low-Side", "power", "W"),
    "PG0U": ("GPU Uncore High Side", "power", "W"),
    "PG0V": ("GPU VRAM Load-Side", "power", "W"),
    "PG1A": ("GPU Aux Load-Side", "power", "W"),
    "PG1C": ("Ext GPU 1.8V", "power", "W"),
    "PG1F": ("GPU Mem Ctl Load-Side", "power", "W"),
    "PG1S": ("GPU B VDDCI Low-Side", "power", "W"),
    "PG2C": ("Ext GPU 1.05V", "power", "W"),
    "PG3C": ("Ext GPU 1.35V", "power", "W"),
    "PH0F": ("Drive 0 Total", "power", "W"),
    "PH0R": ("HDD1 Low-Side", "power", "W"),
    "PH1F": ("Drive 1 Filtered Low-Side * 16", "power", "W"),
    "PH1R": ("Drive 1", "power", "W"),
    "PH2R": ("Drive 2", "power", "W"),
    "PHDC": ("SSD", "power", "W"),
    "PHPC": ("Heatpipe", "power", "W"),
    "PHSC": ("Thunderbolt", "power", "W"),
    "PHSP": ("Thunderbolt", "power", "W"),
    "PI0R": ("TBT IO High Side", "power", "W"),
    "PLDC": ("LCD Panel", "power", "W"),
    "PM0C": ("Average Memory", "power", "W"),
    "PM0f": ("DIMM Load-Side / SQR(Fan RPM)", "power", "W"),
    "PM1C": ("DDR", "power", "W"),
    "PM2C": ("DDR 1.8V CPU", "power", "W"),
    "PM3C": ("DDR S3.", "power", "W"),
    "PMTR": ("Memory Total", "power", "W"),
    "PN0R": ("MCP VCore", "power", "W"),
    "PN1C": ("Average MCP Memory", "power", "W"),
    "PO3R": ("Other 3.3V High Side", "power", "W"),
    "PO5R": ("Other 5V High Side", "power", "W"),
    "PP0R": ("PBus", "power", "W"),
    "PR0C": ("3.3V S0", "power", "W"),
    "PR0R": ("S0 5.0V", "power", "W"),
    "PR1C": ("Other High Side Current.", "power", "W"),
    "PR1R": ("S3 3.30V", "power", "W"),
    "PR2R": ("S3 5.0V", "power", "W"),
    "PR3C": ("3.3V In S0", "power", "W"),
    "PR3R": ("S5 3.30V", "power", "W"),
    "PR5C": ("3.3V S5", "power", "W"),
    "PS2C": ("S2 Camera", "power", "W"),
    "PSBC": ("PCH Core", "power", "W"),
    "PSDC": ("SSD", "power", "W"),
    "PTHC": ("HP Target", "power", "W"),
    "PTPC": ("T101 Boost/PBus Accuator", "power", "W"),
    "PTPR": ("T25 - Track Pad", "power", "W"),
    "PW0R": ("Wifi Load-Side", "power", "W"),
    "PZ0E": ("Zone 0 Target", "power", "W"),
    "PZ0F": ("Zone 0 Filtered", "power", "W"),
    "PZ0G": ("Zone 0 Average", "power", "W"),
    "PZ0T": ("Zone 0 Abstract Throttle", "power", "W"),
    "PZ1E": ("Zone 1 Target", "power", "W"),
    "PZ1F": ("Zone 1 Filtered", "power", "W"),
    "PZ1G": ("Zone 1 Average", "power", "W"),
    "PZ1T": ("Zone 1 Abstract Throttle", "power", "W"),
    "PZ2E": ("Zone 2 Target", "power", "W"),
    "PZ2F": ("Zone 2 Filtered", "power", "W"),
    "PZ2G": ("Zone 2 Average", "power", "W"),
    "PZ2T": ("Zone 2 Abstract Throttle", "power", "W"),
    "PZ3E": ("Zone 3 Target", "power", "W"),
    "PZ3F": ("Zone 3 Filtered", "power", "W"),
    "PZ3G": ("Zone 3 Average", "power", "W"),
    "PZ3T": ("Zone 3 Abstract Throttle", "power", "W"),
    "PZ4E": ("Zone 4 Target", "power", "W"),
    "PZ4F": ("Zone 4 Filtered", "power", "W"),
    "PZ4G": ("Zone 4 Average", "power", "W"),
    "PZ4T": ("Zone 4 Abstract Throttle", "power", "W"),
    "PZ5E": ("Zone 5 Target", "power", "W"),
    "PZ5F": ("Zone 5 Filtered", "power", "W"),
    "PZ5G": ("Zone 5 Average", "power", "W"),
    "PZ5T": ("Zone 5 Abstract Throttle", "power", "W"),
    "PZAP": ("Airport", "power", "W"),
    "PZBL": ("Backlight", "power", "W"),
    "PZDM": ("Memory", "power", "W"),
    "PZHD": ("SSD", "power", "W"),
    "PZOD": ("ODD(PZOD)", "power", "W"),
    "Pc0R": ("Average Main Chipset", "power", "W"),
    "PDBR": ("Power Delivery Brightness", "power", "W"),
    "PU1R": ("Thunderbolt Left", "power", "W"),
    "PU2R": ("Thunderbolt Right", "power", "W"),
}

ISMCSMC_VOLTAGE: dict[str, tuple[str, str, str]] = {
    "VCAC": ("CPU IA", "voltage", "V"),
    "VCSC": ("CPU System Agent", "voltage", "V"),
    "VC%C": ("CPU Core %", "voltage", "V"),
    "VCTC": ("GPU Intel Graphics", "voltage", "V"),
    "VG%C": ("GPU %", "voltage", "V"),
    "VM%R": ("Memory %", "voltage", "V"),
    "Vb0R": ("CMOS", "voltage", "V"),
    "VD0R": ("DC In", "voltage", "V"),
    "VP0R": ("12V Rail", "voltage", "V"),
    "Vp0C": ("12V VCC", "voltage", "V"),
    "VV2S": ("3V", "voltage", "V"),
    "VR3R": ("3.3V", "voltage", "V"),
    "VV1S": ("5V", "voltage", "V"),
    "VV9S": ("12V", "voltage", "V"),
    "VeES": ("PCI 12V", "voltage", "V"),
    "VV1R": ("CPU VTT", "voltage", "V"),
    "VN1R": ("PCH", "voltage", "V"),
    "VN0C": ("MCH", "voltage", "V"),
    "VH05": ("Main 5V", "voltage", "V"),
    "VV7S": ("Auxiliary 3V", "voltage", "V"),
    "VV3S": ("Standby 3V", "voltage", "V"),
    "VV8S": ("Standby 5V", "voltage", "V"),
    "VBAT": ("Battery", "voltage", "V"),
    "V50R": ("5V Low-Side", "voltage", "V"),
    "VACC": ("ACC", "voltage", "V"),
    "VAPC": ("Wireless", "voltage", "V"),
    "VBLC": ("Backlight Output Boosted", "voltage", "V"),
    "VC0G": ("CPU AXG Low-Side", "voltage", "V"),
    "VC0M": ("CPU Mem Load-Side", "voltage", "V"),
    "VC0S": ("CPU VSA Low-Side", "voltage", "V"),
    "VC1R": ("CPU High Side From EMC1704", "voltage", "V"),
    "VCFR": ("FIVR CPU Supply", "voltage", "V"),
    "VCRP": ("CPU Ripple", "voltage", "V"),
    "VCS0": ("CPU Core", "voltage", "V"),
    "VG0F": ("GPU Frame Buffer Input-Side", "voltage", "V"),
    "VG0I": ("GPU VDDCI Load-Side", "voltage", "V"),
    "VG0S": ("GPU A VDDCI Low-Side", "voltage", "V"),
    "VG0U": ("GPU Uncore High Side", "voltage", "V"),
    "VG1F": ("GPU Frame Buffer Input-Side", "voltage", "V"),
    "VG1S": ("GPU B VDDCI Low-Side", "voltage", "V"),
    "VH0R": ("SSD 3V3 Low-Side", "voltage", "V"),
    "VH1R": ("SSD 3.3V Low-Side", "voltage", "V"),
    "VL3t": ("LCD IR", "voltage", "V"),
    "VM0C": ("1.2V To CPU/MEM Low-Side", "voltage", "V"),
    "VM1C": ("1.8V S3 Low-Side", "voltage", "V"),
    "VN0R": ("Average GFX Vcore", "voltage", "V"),
    "VN1C": ("MCP Memory", "voltage", "V"),
    "VODC": ("ODD", "voltage", "V"),
    "VP0T": ("PSU", "voltage", "V"),
    "VR1R": ("PCH/GPU/TBT Load-Side", "voltage", "V"),
    "VSDC": ("SD Card", "voltage", "V"),
    "VTPC": ("T101 Accuator", "voltage", "V"),
    "VZAP": ("WIFI", "voltage", "V"),
    "VZBL": ("Backlight", "voltage", "V"),
    "VZDM": ("Memory", "voltage", "V"),
    "VZHD": ("SSD", "voltage", "V"),
    "VZOD": ("ODD", "voltage", "V"),
}

ISMCSMC_CURRENT: dict[str, tuple[str, str, str]] = {
    "IC0C": ("CPU Core", "current", "A"),
    "IC1C": ("CPU VccIO", "current", "A"),
    "IC2C": ("CPU VccSA", "current", "A"),
    "IC0R": ("CPU High Side", "current", "A"),
    "IC5R": ("CPU DRAM", "current", "A"),
    "IC8R": ("CPU PLL", "current", "A"),
    "IC0G": ("CPU GFX", "current", "A"),
    "IC0M": ("CPU Memory", "current", "A"),
    "IG0C": ("GPU Rail", "current", "A"),
    "IM0C": ("Memory Controller", "current", "A"),
    "IM0R": ("Memory Rail", "current", "A"),
    "IN0C": ("MCH", "current", "A"),
    "ID0R": ("Mainboard S0 Rail (DC In)", "current", "A"),
    "ID5R": ("Mainboard S5 Rail", "current", "A"),
    "IO0R": ("Misc. Rail", "current", "A"),
    "IB0R": ("Battery Rail", "current", "A"),
    "IPBR": ("Charger BMON", "current", "A"),
    "I50R": ("5V Low-Side", "current", "A"),
    "IAPC": ("WLAN Low-Side", "current", "A"),
    "IBAC": ("Battery", "current", "A"),
    "IBLC": ("Backlight", "current", "A"),
    "IDBR": ("Brightness", "current", "A"),
    "IC0I": ("CPU I/O High Side", "current", "A"),
    "IC0S": ("CPU SA High Side", "current", "A"),
    "IC1R": ("CPU High Side From EMC1704", "current", "A"),
    "IC3C": ("CPU DDR", "current", "A"),
    "ICMC": ("Camera S2", "current", "A"),
    "ICS0": ("CPU Core", "current", "A"),
    "ICS1": ("CPU From CPU IMON", "current", "A"),
    "ICTR": ("CPU Riser 12V High Side", "current", "A"),
    "ID1R": ("CPU 1V5 Average", "current", "A"),
    "ID2E": ("Power Supply 12V Filtered", "current", "A"),
    "ID2I": ("Power Supply 12V Filter Input S7.8", "current", "A"),
    "ID2J": ("Power Supply 12V Max Error", "current", "A"),
    "ID2R": ("Power Supply 12V", "current", "A"),
    "ID2T": ("Power Supply 12V Trend", "current", "A"),
    "IG0F": ("GPU FB Input-Side", "current", "A"),
    "IG0I": ("GPU VDDCI Load-Side", "current", "A"),
    "IG0R": ("GPU High Side", "current", "A"),
    "IG0S": ("GPU A VDDCI Low-Side", "current", "A"),
    "IG0U": ("GPU Uncore High Side", "current", "A"),
    "IG1A": ("GPU Aux Input-Side", "current", "A"),
    "IG1C": ("GPU Core Input-Side", "current", "A"),
    "IG1F": ("GPU FB Input-Side", "current", "A"),
    "IG1R": ("GFX B Riser 12V High Side", "current", "A"),
    "IG1S": ("GPU B VDDCI Low-Side", "current", "A"),
    "IG2C": ("Ext GPU 1.05V", "current", "A"),
    "IG3C": ("Ext GPU VRAM & I/O", "current", "A"),
    "IH02": ("HDD 12V Low-Side", "current", "A"),
    "IH05": ("Drive 0 5V Load-Side", "current", "A"),
    "IH0R": ("SSD 3V3 Low-Side", "current", "A"),
    "IH1R": ("SSD 3.3V Low-Side", "current", "A"),
    "IHDC": ("SSD", "current", "A"),
    "IHSC": ("Thunderbolt", "current", "A"),
    "IHSP": ("Thunderbolt", "current", "A"),
    "II0R": ("TBT IO High Side", "current", "A"),
    "ILDC": ("LCD Panel", "current", "A"),
    "IM1C": ("1.8V S3 Low-Side", "current", "A"),
    "IM2C": ("LPDDR 1.8V", "current", "A"),
    "IM3C": ("DDR S3", "current", "A"),
    "IMTR": ("Memory 1V5 High Side", "current", "A"),
    "IN0R": ("GFX Vcore Average", "current", "A"),
    "IN1C": ("MCP DDR", "current", "A"),
    "IN1R": ("PCH Low-Side", "current", "A"),
    "IO3R": ("Current Other 3.3V High", "current", "A"),
    "IO5R": ("Battery BMON", "current", "A"),
    "IODC": ("ODD", "current", "A"),
    "IP0R": ("Battery Discrete", "current", "A"),
    "IPB1": ("Discrete Battery", "current", "A"),
    "IR0C": ("3.3V S0", "current", "A"),
    "IR1C": ("Other High Side", "current", "A"),
    "IR1R": ("PCH/GPU/TBT 1.05V High Side", "current", "A"),
    "IR2C": ("S3 5.0V", "current", "A"),
    "IR3C": ("3.3V S0", "current", "A"),
    "IR5C": ("5.0V S0", "current", "A"),
    "IS2C": ("S2 Camera", "current", "A"),
    "ISBC": ("PCH Core", "current", "A"),
    "ISDC": ("SSD", "current", "A"),
    "ITPC": ("Trackpad Actuator", "current", "A"),
    "IW0R": ("Wifi Low-Side", "current", "A"),
    "IZAP": ("WLAN", "current", "A"),
    "IZBL": ("LCD Backlight", "current", "A"),
    "IZDM": ("1V5S3", "current", "A"),
    "IZHD": ("HDD", "current", "A"),
    "IZOD": ("ODD", "current", "A"),
    "IZOP": ("Airport", "current", "A"),
    "Ic0R": ("CSreg", "current", "A"),
    "IU1R": ("Thunderbolt Left", "current", "A"),
    "IU2R": ("Thunderbolt Right", "current", "A"),
}


def _expand_ismc_wildcards(
    raw: dict[str, tuple[str, str, str]],
) -> dict[str, tuple[str, str, str]]:
    """Expand iSMC % placeholders (single digit 0–9) to concrete four-char keys."""
    out: dict[str, tuple[str, str, str]] = {}
    for key, meta in raw.items():
        if '%' not in key:
            out[key] = meta
            continue
        name_t, cat, unit = meta
        for i in range(10):
            rk = key.replace('%', str(i), 1)
            rn = name_t.replace('%', str(i + 1), 1)
            out[rk] = (rn, cat, unit)
    return out


ISMCSMC_ELECTRICAL_KEYS: dict[str, tuple[str, str, str]] = {}
for _tbl in (ISMCSMC_POWER, ISMCSMC_VOLTAGE, ISMCSMC_CURRENT):
    ISMCSMC_ELECTRICAL_KEYS.update(_expand_ismc_wildcards(_tbl))
