"""System setup and administration commands."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from trcc.cli import _cli_handler


def _sudo_reexec(subcommand):
    """Re-exec `trcc <subcommand>` as root via sudo with correct PYTHONPATH.

    Only includes the trcc package directory — user site-packages are excluded
    to prevent privilege escalation via malicious packages in ~/.local/lib.
    """
    # __file__ is trcc/cli/_system.py — 3 levels up to reach src/ (PYTHONPATH root)
    trcc_pkg = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    cmd = [
        "sudo", "env", f"PYTHONPATH={trcc_pkg}",
        sys.executable, "-m", "trcc.cli", subcommand,
    ]
    print("Root required — requesting sudo...")
    result = subprocess.run(cmd)
    return result.returncode


def _sudo_run(cmd):
    """Run a command with sudo prepended. Returns subprocess.CompletedProcess."""
    return subprocess.run(["sudo"] + cmd)


def show_info():
    """Show system metrics."""
    try:
        from trcc.adapters.system.info import format_metric, get_all_metrics

        metrics = get_all_metrics()

        print("System Information")
        print("=" * 40)

        groups = [
            ("CPU", ['cpu_temp', 'cpu_percent', 'cpu_freq']),
            ("GPU", ['gpu_temp', 'gpu_usage', 'gpu_clock']),
            ("Memory", ['mem_percent']),
            ("Date/Time", ['date', 'time', 'weekday']),
        ]
        for label, keys in groups:
            print(f"\n{label}:")
            for key in keys:
                val = getattr(metrics, key, None)
                if val is not None:
                    print(f"  {key}: {format_metric(key, val)}")

        return 0
    except Exception as e:
        print(f"Error getting metrics: {e}")
        return 1


@_cli_handler
def setup_udev(dry_run=False):
    """Generate and install udev rules + USB storage quirks from KNOWN_DEVICES.

    Without quirks, UAS claims these LCD devices and the kernel ignores them
    (no /dev/sgX created). The :u quirk forces usb-storage bulk-only transport.
    """
    from trcc.adapters.device.detector import (
        _BULK_DEVICES,
        _HID_LCD_DEVICES,
        _LED_DEVICES,
        KNOWN_DEVICES,
    )

    # Always include ALL devices in udev rules (so hardware is ready
    # when users plug in HID/bulk devices, even without --testing-hid)
    all_devices = {**KNOWN_DEVICES, **_HID_LCD_DEVICES, **_LED_DEVICES, **_BULK_DEVICES}

    # --- 1. udev rules (permissions) ---
    rules_path = "/etc/udev/rules.d/99-trcc-lcd.rules"
    rules_lines = ["# Thermalright LCD/LED cooler devices — auto-generated by trcc setup-udev"]

    for (vid, pid), info in sorted(all_devices.items()):
        vendor = info.vendor
        product = info.product
        protocol = info.protocol
        if protocol == "hid":
            rules_lines.append(
                f'# {vendor} {product}\n'
                f'SUBSYSTEM=="hidraw", '
                f'ATTRS{{idVendor}}=="{vid:04x}", '
                f'ATTRS{{idProduct}}=="{pid:04x}", '
                f'MODE="0666"\n'
                f'SUBSYSTEM=="usb", '
                f'ATTR{{idVendor}}=="{vid:04x}", '
                f'ATTR{{idProduct}}=="{pid:04x}", '
                f'MODE="0666"'
            )
        elif protocol == "bulk":
            rules_lines.append(
                f'# {vendor} {product}\n'
                f'SUBSYSTEM=="usb", '
                f'ATTR{{idVendor}}=="{vid:04x}", '
                f'ATTR{{idProduct}}=="{pid:04x}", '
                f'MODE="0666"'
            )
        else:
            rules_lines.append(
                f'# {vendor} {product}\n'
                f'SUBSYSTEM=="scsi_generic", '
                f'ATTRS{{idVendor}}=="{vid:04x}", '
                f'ATTRS{{idProduct}}=="{pid:04x}", '
                f'MODE="0666"'
            )

    rules_content = "\n\n".join(rules_lines) + "\n"

    # --- 2. usb-storage quirks (UAS bypass) ---
    quirk_entries = [f"{vid:04x}:{pid:04x}:u" for vid, pid in sorted(KNOWN_DEVICES)]
    quirks_param = ",".join(quirk_entries)

    # modprobe config (persistent across reboots)
    modprobe_path = "/etc/modprobe.d/trcc-lcd.conf"
    modprobe_content = (
        "# Thermalright LCD — force usb-storage bulk-only (bypass UAS)\n"
        "# Without this, devices are ignored and /dev/sgX is never created\n"
        "# Auto-generated by trcc setup-udev\n"
        f"options usb-storage quirks={quirks_param}\n"
    )

    if dry_run:
        print("=== udev rules ===")
        print(rules_content)
        print(f"# Would write to {rules_path}\n")
        print("=== usb-storage quirks ===")
        print(modprobe_content)
        print(f"# Would write to {modprobe_path}")
        return 0

    # Need root — re-exec with sudo automatically
    if os.geteuid() != 0:
        return _sudo_reexec("setup-udev")

    # Write udev rules
    with open(rules_path, "w") as f:
        f.write(rules_content)
    print(f"Wrote {rules_path}")

    # Write modprobe config
    with open(modprobe_path, "w") as f:
        f.write(modprobe_content)
    print(f"Wrote {modprobe_path}")

    # Apply quirks immediately (without reboot)
    quirks_sysfs = "/sys/module/usb_storage/parameters/quirks"
    if os.path.exists(quirks_sysfs):
        with open(quirks_sysfs, "w") as f:
            f.write(quirks_param)
        print(f"Applied quirks: {quirks_param}")

    # Reload udev
    subprocess.run(["udevadm", "control", "--reload-rules"], check=False)
    subprocess.run(["udevadm", "trigger"], check=False)
    print("\nDone. Unplug and replug the USB cable (or reboot if it's not easily accessible).")
    return 0


def setup_selinux():
    """Install SELinux policy module allowing USB device access.

    Compiles trcc_usb.te -> .mod -> .pp, then loads via semodule.
    Required on SELinux-enforcing systems (Bazzite, Silverblue) where
    detach_kernel_driver() is silently blocked.
    """
    import shutil
    import tempfile

    # Must be root
    if os.geteuid() != 0:
        return _sudo_reexec("setup-selinux")

    # Check if SELinux is enforcing
    try:
        r = subprocess.run(
            ["getenforce"], capture_output=True, text=True, timeout=5,
        )
        status = r.stdout.strip().lower()
    except FileNotFoundError:
        print("SELinux not installed — nothing to do.")
        return 0

    if status != 'enforcing':
        print(f"SELinux is {status} — no policy needed.")
        return 0

    # Check if already loaded
    try:
        r = subprocess.run(
            ["semodule", "-l"], capture_output=True, text=True, timeout=10,
        )
        if 'trcc_usb' in r.stdout:
            print("SELinux module trcc_usb already loaded.")
            return 0
    except FileNotFoundError:
        print("semodule not found — cannot manage SELinux policies.")
        return 1

    # Check for checkmodule and semodule_package
    from trcc.adapters.infra.doctor import _detect_pkg_manager, _install_hint
    pm = _detect_pkg_manager()

    missing: list[str] = []
    for tool in ('checkmodule', 'semodule_package'):
        if not shutil.which(tool):
            missing.append(tool)
    if missing:
        for tool in missing:
            print(f"  {tool} not found — {_install_hint(tool, pm)}")
        return 1

    # Find .te source (shipped in package data)
    # __file__ is trcc/cli/_system.py — parent.parent = trcc/
    trcc_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    te_src = os.path.join(trcc_root, 'data', 'trcc_usb.te')
    if not os.path.isfile(te_src):
        print(f"SELinux policy source not found: {te_src}")
        return 1

    # Compile and install in temp directory
    try:
        with tempfile.TemporaryDirectory() as tmp:
            import shutil as sh
            te_path = os.path.join(tmp, 'trcc_usb.te')
            mod_path = os.path.join(tmp, 'trcc_usb.mod')
            pp_path = os.path.join(tmp, 'trcc_usb.pp')

            sh.copy2(te_src, te_path)

            # checkmodule -M -m -o trcc_usb.mod trcc_usb.te
            r = subprocess.run(
                ['checkmodule', '-M', '-m', '-o', mod_path, te_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                print(f"checkmodule failed: {r.stderr.strip()}")
                return 1

            # semodule_package -o trcc_usb.pp -m trcc_usb.mod
            r = subprocess.run(
                ['semodule_package', '-o', pp_path, '-m', mod_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                print(f"semodule_package failed: {r.stderr.strip()}")
                return 1

            # semodule -i trcc_usb.pp
            r = subprocess.run(
                ['semodule', '-i', pp_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                print(f"semodule install failed: {r.stderr.strip()}")
                return 1

        print("Installed SELinux module trcc_usb (USB device access for TRCC).")
        return 0

    except Exception as e:
        print(f"Error installing SELinux policy: {e}")
        return 1


def install_desktop():
    """Install .desktop menu entry and icon for app launchers.

    Works from both pip install and git clone — generates .desktop inline
    and resolves icons from the package tree (src/trcc/assets/icons/).
    """
    import shutil

    home = Path.home()
    app_dir = home / ".local" / "share" / "applications"

    # Icons live inside the package (works for both pip install and git clone)
    # __file__ is trcc/cli/_system.py — parent.parent = trcc/
    icon_pkg_dir = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) / "assets" / "icons"

    # Generate .desktop content inline (no dependency on repo root)
    desktop_content = """\
[Desktop Entry]
Name=TRCC Linux
Comment=Thermalright LCD Control Center
Exec=trcc gui
Icon=trcc
Terminal=false
Type=Application
Categories=Utility;System;
Keywords=thermalright;lcd;cooler;aio;cpu;
StartupWMClass=trcc-linux
"""

    # Install .desktop file
    app_dir.mkdir(parents=True, exist_ok=True)
    desktop_dst = app_dir / "trcc-linux.desktop"
    desktop_dst.write_text(desktop_content)
    print(f"Installed {desktop_dst}")

    # Install icons to XDG hicolor theme
    installed_icon = False
    for size in [256, 128, 64, 48]:
        icon_src = icon_pkg_dir / f"trcc_{size}x{size}.png"
        if icon_src.exists():
            icon_dir = home / ".local" / "share" / "icons" / "hicolor" / f"{size}x{size}" / "apps"
            icon_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(icon_src, icon_dir / "trcc.png")
            installed_icon = True

    if installed_icon:
        # Update icon cache
        subprocess.run(
            ["gtk-update-icon-cache", str(home / ".local" / "share" / "icons" / "hicolor")],
            check=False, capture_output=True
        )
    else:
        print("Warning: icons not found, menu entry will use a generic icon")

    print("\nTRCC should now appear in your application menu.")
    print("If it doesn't show up immediately, log out and back in.")
    return 0


def uninstall(*, yes: bool = False):
    """Remove all TRCC config, udev rules, autostart, and desktop files."""
    import shutil

    from trcc.conf import Settings

    # Clear resolution markers before wiping config dir
    Settings.clear_installed_resolutions()

    home = Path.home()

    # Files that require root to remove
    root_files = [
        "/etc/udev/rules.d/99-trcc-lcd.rules",
        "/etc/modprobe.d/trcc-lcd.conf",
    ]

    # User files/dirs to remove
    user_items = [
        home / ".config" / "trcc",                          # config dir
        home / ".trcc",                                      # downloaded themes/web data
    ]
    # Glob for any trcc autostart/desktop files (catches current + legacy names)
    for d in (home / ".config" / "autostart", home / ".local" / "share" / "applications"):
        if d.is_dir():
            user_items.extend(d.glob("trcc*.desktop"))

    removed = []

    # Handle root files — auto-elevate with sudo if needed
    root_exists = [p for p in root_files if os.path.exists(p)]
    if root_exists and os.geteuid() != 0:
        print("Root files found — requesting sudo to remove...")
        result = _sudo_run(["rm", "-f"] + root_exists)
        if result.returncode == 0:
            removed.extend(root_exists)
            _sudo_run(["udevadm", "control", "--reload-rules"])
            _sudo_run(["udevadm", "trigger"])
    else:
        for path_str in root_exists:
            os.remove(path_str)
            removed.append(path_str)

    # Handle user files/dirs
    for path in user_items:
        if path.exists():
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
            removed.append(str(path))

    if removed:
        print("Removed:")
        for item in removed:
            print(f"  {item}")
    else:
        print("Nothing to remove — TRCC is already clean.")

    # Reload udev if we removed rules (and we're root — non-root already did it above)
    if os.geteuid() == 0 and any("udev" in r for r in removed):
        subprocess.run(["udevadm", "control", "--reload-rules"], check=False)
        subprocess.run(["udevadm", "trigger"], check=False)

    # Uninstall the pip package itself
    print("\nUninstalling trcc-linux pip package...")
    pip_cmd = [sys.executable, "-m", "pip", "uninstall", "trcc-linux"]
    if yes:
        pip_cmd.append("--yes")
    subprocess.run(pip_cmd, check=False)

    return 0


def report():
    """Generate a full diagnostic report for bug reports."""
    from trcc.adapters.infra.debug_report import DebugReport

    rpt = DebugReport()
    rpt.collect()
    print(rpt)
    return 0


def download_themes(pack=None, show_list=False, force=False, show_info=False):
    """Download theme packs (like spacy download)."""
    try:
        from trcc.adapters.infra.theme_downloader import download_pack, list_available
        from trcc.adapters.infra.theme_downloader import show_info as pack_info

        if show_list or pack is None:
            list_available()
            return 0

        if show_info:
            pack_info(pack)
            return 0

        if force:
            from trcc.conf import Settings
            Settings.clear_installed_resolutions()

        return download_pack(pack, force=force)

    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        return 1


def _confirm(prompt: str, auto_yes: bool) -> bool:
    """Ask [Y/n] question. Returns True on yes/enter, False on n."""
    if auto_yes:
        print(f"  {prompt} [Y/n]: y (auto)")
        return True
    try:
        answer = input(f"  {prompt} [Y/n]: ").strip().lower()
        return answer in ('', 'y', 'yes')
    except (EOFError, KeyboardInterrupt):
        print()
        return False


def run_setup(auto_yes: bool = False) -> int:
    """Interactive setup wizard — check deps, install missing, configure system."""
    from trcc.adapters.infra.doctor import (
        check_desktop_entry,
        check_gpu,
        check_selinux,
        check_system_deps,
        check_udev,
        get_setup_info,
    )

    info = get_setup_info()
    print(f"\n  TRCC Setup — {info.distro}\n")

    actions: list[str] = []

    # -- Step 1/5: System dependencies --
    print("  Step 1/5: System dependencies")
    deps = check_system_deps(info.pkg_manager)
    missing_required: list[str] = []
    missing_optional: list[str] = []

    for dep in deps:
        if dep.ok:
            ver = f" {dep.version}" if dep.version else ""
            print(f"    [OK]  {dep.name}{ver}")
        elif dep.required:
            note = f" ({dep.note})" if dep.note else ""
            print(f"    [!!]  {dep.name} — MISSING{note}")
            missing_required.append(dep.install_cmd)
        else:
            note = f" ({dep.note})" if dep.note else ""
            print(f"    [--]  {dep.name} — not installed{note}")
            missing_optional.append(dep.install_cmd)

    # Offer to install missing required deps
    for cmd in missing_required:
        if _confirm(f"Install? -> {cmd}", auto_yes):
            print(f"    -> {cmd}")
            result = subprocess.run(cmd.split())
            if result.returncode == 0:
                actions.append(f"Installed: {cmd}")
            else:
                print(f"    [!!] Command failed (exit {result.returncode})")

    # Offer to install missing optional deps
    for cmd in missing_optional:
        if _confirm(f"Install? -> {cmd}", auto_yes):
            print(f"    -> {cmd}")
            result = subprocess.run(cmd.split())
            if result.returncode == 0:
                actions.append(f"Installed: {cmd}")

    print()

    # -- Step 2/5: GPU detection --
    print("  Step 2/5: GPU detection")
    gpus = check_gpu()
    if not gpus:
        print("    [--]  No discrete GPU detected")
    for gpu in gpus:
        if gpu.package_installed:
            print(f"    [OK]  {gpu.label}")
        else:
            print(f"    [--]  {gpu.label} — {gpu.install_cmd}")
            if _confirm(
                f"Install? -> {gpu.install_cmd}", auto_yes,
            ):
                print(f"    -> {gpu.install_cmd}")
                result = subprocess.run(
                    [sys.executable, "-m", "pip", "install"]
                    + gpu.install_cmd.split()[-1:],
                )
                if result.returncode == 0:
                    actions.append(f"Installed: {gpu.install_cmd}")
                else:
                    print(f"    [!!] pip failed (exit {result.returncode})")
    print()

    # -- Step 3/5: USB device permissions --
    print("  Step 3/5: USB device permissions")
    udev = check_udev()
    if udev.ok:
        print(f"    [OK]  {udev.message}")
    else:
        print(f"    [!!]  {udev.message}")
        if _confirm(
            "Install udev rules? (requires sudo)", auto_yes,
        ):
            rc = setup_udev()
            if rc == 0:
                actions.append("Installed udev rules")
            else:
                print("    [!!] udev setup failed")
    print()

    # -- Step 4/5: SELinux policy --
    se = check_selinux()
    if se.enforcing:
        print("  Step 4/5: SELinux policy")
        if se.ok:
            print(f"    [OK]  {se.message}")
        else:
            print(f"    [!!]  {se.message}")
            if _confirm(
                "Install SELinux USB policy? (requires sudo)", auto_yes,
            ):
                rc = setup_selinux()
                if rc == 0:
                    actions.append("Installed SELinux policy")
                else:
                    print("    [!!] SELinux setup failed")
        print()

    # -- Step 5/5: Desktop integration --
    print("  Step 5/5: Desktop integration")
    if check_desktop_entry():
        print("    [OK]  Application menu entry installed")
    else:
        print("    [--]  No application menu entry")
        if _confirm(
            "Install application menu entry?", auto_yes,
        ):
            rc = install_desktop()
            if rc == 0:
                actions.append("Installed desktop entry")
    print()

    # -- Summary --
    print("  Summary")
    if actions:
        for a in actions:
            print(f"    + {a}")
    else:
        print("    Nothing to do — system is ready.")

    print("\n  Run 'trcc gui' to launch, or find TRCC in your app menu.\n")
    return 0
